name: Main workflow
on: push

jobs:
        BuildForMac:
                name: BuildForMac
                runs-on: macOS-10.14
                steps:
                        - name: CloneRepository
                          run: git clone https://github.com/Trzyszcz/Fountain.git
                        - name: DebugInfo1
                          run: ls -a
                        - name: ChangeDirectory
                          run: cd Fountain
                        - name: DebugInfo2
                          run: ls -a
                        - name: BuildStuff
                          run: g++ test.cpp Binasc.cpp MidiEvent.cpp MidiEventList.cpp MidiFile.cpp MidiMessage.cpp Options.cpp 
