name: Main workflow
on: push

jobs:
        BuildForMac:
                name: BuildForMac
                runs-on: macOS-latest
                steps:
                        - name: CloneRepository
                          run: git clone https://github.com/Trzyszcz/Fountain.git
                          #- name: DebugInfo1
                          #run: ls -a
                          #- name: ChangeDirectory
                          #run: cd Fountain
                          #- name: DebugInfo2
                          #run: ls -a
                        - name: BuildStuff
                          run: g++ Fountain/test.cpp Fountain/Binasc.cpp Fountain/MidiEvent.cpp Fountain/MidiEventList.cpp Fountain/MidiFile.cpp Fountain/MidiMessage.cpp Fountain/Options.cpp 
